### ISSUE TITLE
Contributing Markdown file

### ISSUE THREAD

**Issue by AnthonyMa2122** [omegabytes/csc648group06#26]
Create a markdown that shows contributions from each team member. 

*May want to append contributions to initial README for our final product

**Comment by omegabytes** [comment]
You can link to the contributions file in the readme. Usually you put that up top, something like "welcome to our project, this is what it does, if you're interested in contributing please check _contributions.md_"

Since this is not open source, this is more of a guideline for our team. It should cover:

- branching
- issues
- pull requests into master
- who can work in the team account and when
- code quality (working before submit to dev, etc)
- when code reviews are required, and how to ask for one
- code standards (tabs = how many spaces, documentation requirements, variable naming conventions, etc). The team will need to talk about this as we move from planning to coding.

This may seem like a lot, but it really does get us all prepared to work in the industry. My goal for this team and this project is to have a repository we can all show to future employers that shows some really good habits. This will more than make up for any lack of experience we have coming in.

[Here](https://github.com/rLoopTeam/eng-software-pod/blob/development/CONTRIBUTING.md) is the one I made for my last project if you'd like a template.
